hashgraph/hedera-agent-kit-js

- src/agent/index.ts
- src/langchain/index.ts
- src/tools/hts/queries/balance.ts
- src/tools/hts/queries/index.js
- src/tools/hts/queries/index.ts
- src/tools/hts/transactions/airdrop.ts
- src/tools/hts/transactions/index.ts
- src/tools/hts/transactions/transfer.ts
> add tools for airdrop, token transfer, query balance

- src/langchain/index.ts
> extend langchain tools with hts

- src/langchain/index.ts
> Langchain extended support

- src/agent/index.ts
> remove localnode causing build error

- package-lock.json
- package.json
- src/tests/utils/utils.ts
Updates to latest dependencies + switches to `tsx` for node runner
> chore: update deps

- package.json
- src/examples/langchain.ts
- src/shared/hedera-utils/hedera-parameter-normaliser.ts
- src/shared/hedera-utils/mirrornode/hedera-mirrornode-service-default-impl.ts
- src/shared/hedera-utils/mirrornode/hedera-mirrornode-service.interface.ts
- src/shared/hedera-utils/mirrornode/hedera-mirrornode-utils.ts
- src/shared/hedera-utils/mirrornode/types.ts
- src/shared/parameter-schemas/account-query.zod.ts
- src/shared/tools/queries/get-account-query.ts
- src/shared/tools/queries/get-account-token-balances-query.ts
- src/shared/tools/queries/get-hbar-balance-query.ts
- src/shared/tools/queries/get-topic-messages-query.ts
- Removed `web-streams-polyfill` from dependencies in `package.json`.
- Updated `accountId` in `langchain.ts` for improved functionality.
- Changed `returnIntermediateSteps` to `false` in `AgentExecutor` for better performance.
- Added new normalization methods in `HederaParameterNormaliser` for HBAR balance and token balances.
- Introduced `IHederaMirrornodeService` interface for better type safety.
- Updated query tools to utilize normalized parameters and improved error handling.
- Enhanced topic messages query to support new timestamp parameters and convert messages from base64.
If this PR fixes a bug or resolves a feature request, link it …
> Refactor Hedera integration and enhance query tools

- modelcontextprotocol/src/index.ts
- typescript/package-lock.json
- typescript/package.json
- typescript/src/shared/hedera-utils/mirrornode/hedera-mirrornode-service-default-impl.ts
- typescript/src/shared/hedera-utils/mirrornode/types.ts
- typescript/src/shared/parameter-schemas/account-query.zod.ts
- typescript/src/shared/tools/consensus/create-topic.ts
- typescript/src/shared/tools/consensus/submit-topic-message.ts
- typescript/src/shared/tools/fungible-token/airdrop-fungible-token.ts
- typescript/src/shared/tools/fungible-token/create-fungible-token.ts
- typescript/src/shared/tools/non-fungible-token/create-non-fungible-token.ts
- typescript/src/shared/tools/queries/get-account-query.ts
- typescript/src/shared/tools/queries/get-account-token-balances-query.ts
- typescript/src/shared/tools/queries/get-hbar-balance-query.ts
- typescript/src/shared/tools/queries/get-topic-messages-query.ts
> downgraded zod version to fix mcp

- typescript/examples/langchain/package.json
- typescript/examples/langchain/return-bytes-tool-calling-agent.ts
Closes: #66 
@jaycoolh We should probably add a helper function to the kit to retrieve the bytes in the next release of the agent kit
> added example for return bytes

- docs/TOOLS.md
- typescript/src/shared/hedera-utils/hbar-conversion-utils.ts
- typescript/src/shared/tools/queries/get-hbar-balance-query.ts
> #92 tinybar -> hbar conversion for account balance

- contracts/.env.example
- contracts/contracts/BaseERC721.sol
- contracts/contracts/BaseERC721Factory.sol
- contracts/ignition/modules/deploy-factory.ts
- contracts/test/BaseERC721.test.ts
- contracts/test/BaseERC721Factory.test.ts
- docs/TOOLS.md
- typescript/examples/langchain/package-lock.json
- typescript/package-lock.json
- typescript/package.json
- typescript/src/plugins/core-evm-plugin/index.ts
- typescript/src/plugins/core-evm-plugin/tools/erc721/create-erc721.ts
- typescript/src/plugins/core-evm-plugin/tools/erc721/mint-erc721.ts
- typescript/src/shared/constants/contracts.ts
- typescript/src/shared/hedera-utils/hedera-parameter-normaliser.ts
- typescript/src/shared/parameter-schemas/evm.zod.ts
Implemented the factory, Base ERC721 template and the tool itself
Closes: #101
> feat: add create erc721 contract

- docs/adr/002-testing-strategy.md
- typescript/package-lock.json
- typescript/package.json
- typescript/src/shared/hedera-utils/mirrornode/hedera-mirrornode-service.interface.ts
- typescript/src/shared/tools/types.ts
- typescript/test/unit/decimals-utils.test.ts
- typescript/vitest.config.ts
This PR sets up tests with Vitest testing framework
Fixes #200 
**Checklist**
> chore: setup vitest testing configuration

- README.md
- typescript/README.md
- typescript/examples/langchain/package-lock.json
Updated a few things
* Made a note about how to run from source vs. using npm
* Removed metions of TOOLS.md
* Added links to PLUGINS.md
* fixed some minor typos
> docs: updated example and removed outdated content

- typescript/test/e2e/delete-account.e2e.test.ts
- typescript/test/integration/hedera/delete-account.integration.test.ts
- typescript/test/integration/tool-matching/delete-account-tool-matching.integration.test.ts
- typescript/test/unit/parameter-normalization/delete-account-params-normalization.unit.test.ts
- typescript/test/unit/tools/delete-account.unit.test.ts
Includes unit, integration, and end-to-end tests to validate and ensure the reliability of the delete account functionality.
**Checklist**
_(no docs required)_
> test: delete account tool

- docs/HEDERAPLUGINS.md
- typescript/examples/langchain/plugin-tool-calling-agent.ts
- typescript/src/plugins/core-evm-query-plugin/index.ts
- typescript/src/plugins/core-evm-query-plugin/tools/queries/get-contract-info-query.ts
- typescript/src/plugins/core-token-query-plugin/index.ts
- typescript/src/plugins/index.ts
- typescript/src/shared/hedera-utils/mirrornode/hedera-mirrornode-service-default-impl.ts
- typescript/src/shared/hedera-utils/mirrornode/hedera-mirrornode-service.interface.ts
- typescript/src/shared/hedera-utils/mirrornode/types.ts
- typescript/src/shared/parameter-schemas/evm.zod.ts
- typescript/src/shared/parameter-schemas/query.zod.ts
This PR adds `GET_CONTRACT_INFO_QUERY_TOOL` and introduces `coreEVMQueryPlugin`.
**Usage:**
```
Show me details of contract 0.0.123123
```
Fixes #169 
**Notes for reviewer**:
tested with langchain agent
**Checklist**
> feat: add contract info query tool

- typescript/test/e2e/create-account.e2e.test.ts
- typescript/test/e2e/delete-account.e2e.test.ts
- typescript/test/e2e/get-transaction-record.e2e.test.ts
- typescript/test/e2e/transfer-hbar.e2e.test.ts
- typescript/test/e2e/update-account.e2e.test.ts
- typescript/test/integration/hedera/create-account.integration.test.ts
- typescript/test/integration/hedera/delete-account.integration.test.ts
- typescript/test/integration/hedera/get-transaction-record.integration.test.ts
- typescript/test/integration/hedera/transfer-hbar.integration.test.ts
- typescript/test/integration/hedera/update-account.integration.test.ts
- typescript/test/utils/setup/client-setup.ts
- typescript/test/utils/setup/langchain-test-setup.ts
- typescript/vitest.config.ts
Improve parallel tests execution by creating new accounts for each tests
Fixes #252 
**Notes for reviewer**:
**Checklist**
_No docs  needed_
> refactor(test): improve parallel tests execution

- typescript/src/plugins/core-evm-plugin/tools/erc20/create-erc20.ts
- typescript/src/shared/hedera-utils/hedera-parameter-normaliser.ts
- typescript/src/shared/parameter-schemas/evm.zod.ts
- typescript/test/e2e/create-erc20.e2e.test.ts
- typescript/test/integration/hedera/create-erc20.integration.test.ts
- typescript/test/integration/tool-matching/create-erc20-tool-matching.integration.test.ts
- typescript/test/unit/parameter-normalization/create-erc20-params-normalization.unit.test.ts
- typescript/test/unit/tools/create-erc20.unit.test.ts
- typescript/test/utils/hedera-operations/HederaOperationsWrapper.ts
- typescript/test/utils/setup/langchain-test-config.ts
add unit, integration, and e2e tests for create ERC20 token tool
**Notes for reviewer**:
During development of those tests and issue with zod schemas has been spotted. We are currently using them only to generate types but this means that the default values set there are not applied. Due to that I have decided to add parsing with the schema in the params normalization flow with handling of the zod errors.
If this changes will be approved we will need to align all other tools 
**Checklist**
> test: add unit, integration, and e2e tests for create ERC20 token tool

- typescript/test/unit/tools/create-erc20.unit.test.ts
hot fix for changed tools error handling
**Checklist**
> test: update error message assertions in create ERC20 token unit test

- typescript/test/integration/hedera/create-fungible-token.integration.test.ts
- typescript/test/integration/hedera/create-non-fungible-token.integration.test.ts
- typescript/test/integration/tool-matching/mint-fungible-token-tool-matching.integration.test.ts
- typescript/test/integration/tool-matching/sign-schedule-transaction-tool-matching.integration.test.ts
fixes failing tests
**Checklist**
> test: update error message assertions and format in token tools tests

- docs/DEVEXAMPLES.md
> docs: Update DEVEXAMPLES.md

- .github/CODEOWNERS
Update the team name in the CODEOWNERS file to `-maintainers`.
**Related Issue(s)**:
Fixes #310
> chore(fix): Update team name in CODEOWNERS

- typescript/examples/nextjs/README.md
- Add missing environment variable for `AI_PROVIDER` and change the order a bit.
> fix: Update README with environment setup instructions for next example

- docs/HEDERAPLUGINS.md
- typescript/src/plugins/core-consensus-query-plugin/index.ts
- typescript/src/plugins/core-consensus-query-plugin/tools/queries/get-topic-info-query.ts
- typescript/src/shared/hedera-utils/mirrornode/hedera-mirrornode-service-default-impl.ts
- typescript/src/shared/hedera-utils/mirrornode/hedera-mirrornode-service.interface.ts
- typescript/src/shared/hedera-utils/mirrornode/types.ts
- typescript/src/shared/parameter-schemas/consensus.zod.ts
- typescript/test/e2e/get-topic-info.e2e.test.ts
- typescript/test/integration/hedera/get-topic-info.integration.test.ts
- typescript/test/integration/tool-matching/get-topic-info-tool-matching.integration.test.ts
- typescript/test/unit/tools/get-topic-info.unit.test.ts
- typescript/test/utils/setup/langchain-test-config.ts
Get topic info tool
#229 
**Checklist**
> feat: get topic info

- README.md
- typescript/examples/ai-sdk/package-lock.json
- typescript/examples/ai-sdk/package.json
- typescript/examples/ai-sdk/plugin-tool-calling-agent.ts
- typescript/examples/langchain/package-lock.json
- typescript/examples/langchain/package.json
- typescript/examples/langchain/plugin-tool-calling-agent.ts
- typescript/examples/langchain/return-bytes-tool-calling-agent.ts
- typescript/examples/langchain/structured-chat-agent.ts
- typescript/examples/langchain/tool-calling-agent.ts
- typescript/examples/nextjs/package-lock.json
- typescript/examples/nextjs/package.json
- typescript/examples/nextjs/src/lib/agent-config.ts
Update examples to use latest (3.3.0) agent kit tools
#316 
**Checklist**
> feat: update examples to use latest 3.3.0 agent kit tools
